stages:
  - template: azure/stages.yml@templates
    parameters:
      codecov_token: $(CODECOV_TOKEN_SECRET)
      benches: true

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: indiv0
